# Generated by Django 3.2.5 on 2021-07-31 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='expensesb',
        ),
        migrations.RemoveField(
            model_name='data',
            name='expensestt',
        ),
        migrations.AddField(
            model_name='data',
            name='expense',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
